# FAQ data stored in English only for the transformation pipeline.
# This file centralizes 100+ high-quality questions for the translation engine.

ENGLISH_FAQS = [
    # General & About (10)
    {"question": "What is SATYA?", "answer": "SATYA (System for AI-based Transparency and Yielding Assistance) is an AI-powered platform helping Indian citizens discover schemes, verify documents, and check eligibility instantly.", "category": "general"},
    {"question": "How to check eligibility?", "answer": "To check eligibility: 1. Fill your profile. 2. Verify documents with AI. 3. Get personalized scheme lists.", "category": "general"},
    {"question": "How does document verification work?", "answer": "Our AI uses neural OCR and QR scanning to verify documents like Aadhaar, PAN, and Income Certificates in real-time.", "category": "general"},
    {"question": "Is my data safe with SATYA?", "answer": "Yes, SATYA uses end-to-end encryption and we do not store sensitive document images after verification is complete.", "category": "general"},
    {"question": "Who created SATYA?", "answer": "SATYA is developed locally as a multilingual solution for transparent government scheme access.", "category": "general"},
    {"question": "Which states are covered?", "answer": "SATYA covers schemes from all Indian states including Bihar, West Bengal, Maharashtra, Tamil Nadu, and others.", "category": "general"},
    {"question": "Can I apply for schemes through SATYA?", "answer": "SATYA provides verified links and application processes. Actual applications are completed on the official government portals.", "category": "general"},
    {"question": "What documents can be verified?", "answer": "You can verify Aadhaar, PAN Card, Income Certificate, and Caste Certificate using our AI scanner.", "category": "general"},
    {"question": "How to get a SATYA account?", "answer": "Simply use the Sign-Up button in the navigation bar to create your profile.", "category": "general"},
    {"question": "How to use the chatbot?", "answer": "Simply type your question or use the suggested chips. The chatbot automatically detects your language.", "category": "general"},

    # Agriculture (20)
    {"question": "What is PM Kisan?", "answer": "PM-Kisan provides ₹6,000 per year in 3 installments to small and marginal farmers.", "category": "agriculture"},
    {"question": "Who is eligible for PM Kisan?", "answer": "Small and marginal farmers with landholdings up to 2 hectares are typically eligible, subject to state rules.", "category": "agriculture"},
    {"question": "How to apply for PM Kisan?", "answer": "Apply through the official PM-Kisan portal or your local CSC (Common Service Center).", "category": "agriculture"},
    {"question": "What is the Kisan Credit Card (KCC)?", "answer": "KCC provides farmers with timely access to credit for cultivation and maintenance at low interest.", "category": "agriculture"},
    {"question": "What is PM Fasal Bima Yojana?", "answer": "It is a crop insurance scheme protecting farmers against crop loss due to natural calamities.", "category": "agriculture"},
    {"question": "What is Soil Health Card scheme?", "answer": "It provides farmers with soil nutrient status reports to help optimize fertilizer use.", "category": "agriculture"},
    {"question": "What is PM Krishi Sinchayee Yojana?", "answer": "Aims to improve on-farm water use efficiency (Per Drop More Crop) through irrigation.", "category": "agriculture"},
    {"question": "What are the benefits for women farmers?", "answer": "Mahila Kisan Sashaktikaran Pariyojana (MKSP) supports and empowers women in agriculture.", "category": "agriculture"},
    {"question": "How to get a tractor subsidy?", "answer": "Various state schemes and the SMAM (Sub-Mission on Agricultural Mechanization) provide subsidies for farm machinery.", "category": "agriculture"},
    {"question": "What is E-NAM?", "answer": "An online trading platform for agricultural commodities in India.", "category": "agriculture"},
    {"question": "What is PM KUSUM?", "answer": "Provides solar pumps and grid-connected solar power plants to farmers.", "category": "agriculture"},
    {"question": "How to check PM Kisan status?", "answer": "Use the 'Know Your Status' link on the PM-Kisan portal using your registration number.", "category": "agriculture"},
    {"question": "What is the benefit of organic farming schemes?", "answer": "PKVY (Paramparagat Krishi Vikas Yojana) provides financial aid for organic cluster development.", "category": "agriculture"},
    {"question": "What is the Agriculture Infrastructure Fund?", "answer": "Provides medium-long term debt financing for post-harvest management infrastructure.", "category": "agriculture"},
    {"question": "What is Rythu Bharosa?", "answer": "A specific scheme in Andhra Pradesh providing financial aid to farmers.", "category": "agriculture"},
    {"question": "What is the Krushak Assistance for Livelihood and Income Augmentation (KALIA)?", "answer": "Odisha's flagship scheme for farmers' welfare and income support.", "category": "agriculture"},
    {"question": "How to get a cattle loan?", "answer": "Schemes like the Animal Husbandry Infrastructure Development Fund (AHIDF) provide credit for dairy and meat processing.", "category": "agriculture"},
    {"question": "What is PM Matsya Sampada Yojana?", "answer": "Focuses on the sustainable development of the fisheries sector.", "category": "agriculture"},
    {"question": "What is the mission for bee-keeping?", "answer": "The National Beekeeping and Honey Mission (NBHM) promotes scientific beekeeping.", "category": "agriculture"},
    {"question": "What is the Rashtriya Krishi Vikas Yojana (RKVY)?", "answer": "A holistic scheme for the development of agriculture and allied sectors.", "category": "agriculture"},

    # Housing & Infrastructure (15)
    {"question": "What is PM Awas Yojana (PMAY)?", "answer": "Provides housing for all by providing subsidies to build or buy affordable houses.", "category": "housing"},
    {"question": "Difference between PMAY-Urban and PMAY-Gramin?", "answer": "PMAY-U focuses on city dwellers, while PMAY-G focuses on rural households.", "category": "housing"},
    {"question": "How to apply for PMAY?", "answer": "Apply through the official PMAY portal or your local municipal/panchayat office.", "category": "housing"},
    {"question": "What is the subsidy for PMAY home loans?", "answer": "The Credit Linked Subsidy Scheme (CLSS) provides interest subsidies based on income categories.", "category": "housing"},
    {"question": "What is Swachh Bharat Mission?", "answer": "Aims to achieve universal sanitation and eliminate open defecation across India.", "category": "housing"},
    {"question": "How to get a toilet subsidy?", "answer": "Eligible households can apply through the local SBM (Gramin/Urban) office for financial aid to build toilets.", "category": "housing"},
    {"question": "What is the PM-SVANidhi scheme?", "answer": "A micro-credit scheme for street vendors to enable them to restart their livelihood.", "category": "housing"},
    {"question": "What is the Ujjwala scheme?", "answer": "Provides free LPG connections to women from BPL households.", "category": "housing"},
    {"question": "What is Saubhagya Yojana?", "answer": "Aims to provide electricity connections to all un-electrified households.", "category": "housing"},
    {"question": "What is Jal Jeevan Mission?", "answer": "Provides tap water connections to every rural household by 2024.", "category": "housing"},
    {"question": "Is there a scheme for slum dwellers?", "answer": "PMAY-Urban has specific provisions for 'In-situ Slum Redevelopment' using land as a resource.", "category": "housing"},
    {"question": "What is PM-Gati Shakti?", "answer": "A national master plan for multi-modal connectivity to reduce logistics costs.", "category": "housing"},
    {"question": "How to check PMAY list?", "answer": "Search for your name in the PMAY beneficiary list using your Aadhaar or ID on the official portal.", "category": "housing"},
    {"question": "What is Smart Cities Mission?", "answer": "An urban renewal program to develop sustainable and citizen-friendly cities.", "category": "housing"},
    {"question": "What is HRIDAY scheme?", "answer": "Focuses on the conservation and revitalization of heritage cities.", "category": "housing"},

    # Healthcare (20)
    {"question": "What is Ayushman Bharat?", "answer": "Provides healthcare insurance of ₹5 lakh per family per year for secondary and tertiary hospitalization.", "category": "health"},
    {"question": "How to get Ayushman Card?", "answer": "Check your eligibility on the PM-JAY website and visit a common service center to get your PMJAY card.", "category": "health"},
    {"question": "Is PM-JAY applicable in private hospitals?", "answer": "Yes, it is applicable in all government and empanelled private hospitals.", "category": "health"},
    {"question": "What is Jan Aushadhi?", "answer": "Provides generic medicines at affordable prices through PMBI centers.", "category": "health"},
    {"question": "What is Poshan Abhiyaan?", "answer": "India's flagship program to improve nutritional outcomes for children, pregnant women, and lactating mothers.", "category": 'health'},
    {"question": "What is Mission Indradhanush?", "answer": "A universal immunization program ensuring full coverage for all children.", "category": "health"},
    {"question": "How to apply for Maternity Benefits?", "answer": "PM Matru Vandana Yojana (PMMVY) provides cash incentives to pregnant and lactating mothers.", "category": "health"},
    {"question": "What is Health ID / ABHA?", "answer": "A unique health ID to store and share health records digitally across India.", "category": "health"},
    {"question": "What is the benefit of TB free India mission?", "answer": "The Nikshay Poshan Yojana provides ₹500/month to TB patients for nutritional support.", "category": "health"},
    {"question": "What is Mission Shakti?", "answer": "An integrated women empowerment program focusing on safety and economic empowerment.", "category": "health"},
    {"question": "How to get a disability certificate?", "answer": "Apply through the UDID (Unique Disability ID) portal with medical reports.", "category": "health"},
    {"question": "What is NIRAMAYA Health Insurance?", "answer": "Affordable health insurance for persons with autism, cerebral palsy, etc.", "category": "health"},
    {"question": "What is the National Ambulance Service number?", "answer": "Dial 102 or 108 for emergency medical and ambulance services.", "category": "health"},
    {"question": "What is PM SURAJ?", "answer": "National portal for credit support to sanitation workers and marginalized groups.", "category": "health"},
    {"question": "Are there schemes for mental health?", "answer": "Tele MANAS provides free 24/7 mental health counseling across India.", "category": "health"},
    {"question": "What is the Free Dialysis scheme?", "answer": "PM National Dialysis Program provides free dialysis to BPL families in district hospitals.", "category": "health"},
    {"question": "What is Suraksha Bima Yojana?", "answer": "An accidental insurance scheme providing ₹2 lakh cover for a very low annual premium.", "category": "health"},
    {"question": "What is Jeevan Jyoti Bima Yojana?", "answer": "A life insurance scheme providing ₹2 lakh cover for a low annual premium.", "category": "health"},
    {"question": "How to avail free heart surgeries for children?", "answer": "Rashtriya Bal Swasthya Karyakram (RBSK) provides free treatment for specific ailments in children.", "category": "health"},
    {"question": "What is the National Health Mission (NHM)?", "answer": "Aims to provide universal access to equitable, affordable, and quality healthcare.", "category": "health"},

    # Education & Skills (15)
    {"question": "What is PM-SHRI?", "answer": "A scheme for development of schools into model schools with modern education standards.", "category": "education"},
    {"question": "How to apply for Post-Matric Scholarship?", "answer": "Apply through the National Scholarship Portal (NSP) based on your category and income.", "category": "education"},
    {"question": "What is Skill India?", "answer": "A mission to provide vocational training and certification to Indian youth.", "category": "education"},
    {"question": "How to get PMKVY training?", "answer": "Pradhan Mantri Kaushal Vikas Yojana centers provide free skill training. Register on the NSDC portal.", "category": "education"},
    {"question": "What is Vidyanjali?", "answer": "A school volunteer program helping community members to support government schools.", "category": "education"},
    {"question": "What is NIPUN Bharat?", "answer": "Aims to achieve foundational literacy and numeracy for every child by Grade 3.", "category": "education"},
    {"question": "Are there scholarships for girl students?", "answer": "Schemes like Pragati Scholarship and National Scheme of Incentive to Girls provide financial aid.", "category": "education"},
    {"question": "What is the PM Research Fellowship?", "answer": "Supports doctoral students in IISc, IITs, etc., for advanced research.", "category": "education"},
    {"question": "What is the National Education Policy (NEP) 2020?", "answer": "A comprehensive framework for transforming education from preschool to higher education.", "category": "education"},
    {"question": "What is Samagra Shiksha?", "answer": "An overarching program for the school education sector from pre-school to class 12.", "category": "education"},
    {"question": "How to use E-Shala?", "answer": "An online portal for resources and digital contents for teachers and students.", "category": "education"},
    {"question": "What is Mid-Day Meal?", "answer": "Provides nutritional meals to students in government schools to improve attendance.", "category": "education"},
    {"question": "How to apply for study abroad loans?", "answer": "Various public banks provide education loans under state-backed interest subsidy schemes.", "category": "education"},
    {"question": "What is DIKSHA portal?", "answer": "A national digital infrastructure for teachers for school education.", "category": "education"},
    {"question": "What is Padhe Bharat Badhe Bharat?", "answer": "A sub-program focusing on enhancing language and math skills in early grades.", "category": "education"},

    # Finance & Jobs (15)
    {"question": "What is Mudra Loan?", "answer": "Provides loans up to ₹10 lakh for non-corporate, non-farm small/micro enterprises.", "category": "finance"},
    {"question": "Levels of Mudra Loans?", "answer": "Shishu (up to ₹50,000), Kishor (₹50k-₹5L), and Tarun (₹5L-₹10L).", "category": "finance"},
    {"question": "What is PM Jan Dhan Yojana?", "answer": "Provides universal access to banking services with accounts, credit, and insurance.", "category": "finance"},
    {"question": "How to get an overdraft in Jan Dhan account?", "answer": "Eligible account holders can get an overdraft limit up to ₹10,000 after 6 months of use.", "category": "finance"},
    {"question": "What is Startup India?", "answer": "An initiative to nurture startups and drive economic growth via tax breaks and simplified rules.", "category": "finance"},
    {"question": "What is Stand Up India?", "answer": "Facilitates bank loans for SC/ST and Women entrepreneurs for greenfield projects.", "category": "finance"},
    {"question": "What is MGNREGA?", "answer": "Guarantees 100 days of manual work per year to every rural household for livelihood security.", "category": "finance"},
    {"question": "How to get a Job Card?", "answer": "Apply at your Gram Panchayat (Village Council) with identification details.", "category": "finance"},
    {"question": "What is the benefit of the MSME registration (Udyam)?", "answer": "Udyam registration provides priority lending, subsidies, and government tender benefits.", "category": "finance"},
    {"question": "What is Atal Pension Yojana (APY)?", "answer": "A pension scheme for workers in the unorganized sector providing fixed monthly pensions.", "category": "finance"},
    {"question": "What is the PMEGP scheme?", "answer": "Prime Minister's Employment Generation Programme provides subsidies for starting new businesses.", "category": "finance"},
    {"question": "How to apply for an unemployment allowance?", "answer": "Various states offer 'Berozgari Bhatta' under specific eligibility criteria.", "category": "finance"},
    {"question": "What is the Credit Guarantee Scheme?", "answer": "Provides collateral-free loans to micro and small businesses through trust guarantees.", "category": "finance"},
    {"question": "What is PM Vishwakarma?", "answer": "Supports traditional artisans and craftsmen with credit, training, and identity cards.", "category": "finance"},
    {"question": "What is Sukanya Samriddhi Yojana?", "answer": "A small deposit scheme meant for the girl child for her education and marriage.", "category": "finance"},

    # Identity & Certificates (15)
    {"question": "How to link Aadhaar with PAN?", "answer": "Link it on the Income Tax E-filing portal using your details. It is mandatory for tax purposes.", "category": "documents"},
    {"question": "How to update address in Aadhaar?", "answer": "Use the UIDAI 'MyAadhaar' portal with valid address proof or through a resident request code.", "category": "documents"},
    {"question": "What is a Voter ID Card?", "answer": "The EPIC (Election Photo Identity Card) used by citizens to vote in elections.", "category": "documents"},
    {"question": "How to apply for a new Ration Card?", "answer": "Apply through your State Food and Civil Supplies Department portal with family details.", "category": "documents"},
    {"question": "What is the use of an Income Certificate?", "answer": "Mandatory for availing scholarships, fee waivers, and specific government scheme subsidies.", "category": "documents"},
    {"question": "How to get a Caste Certificate?", "answer": "Apply at the Tehsil/E-District office with ancestry proof and community records.", "category": "documents"},
    {"question": "What is Domicile Certificate?", "answer": "A document proving a person is a permanent resident of a specific state.", "category": "documents"},
    {"question": "How to apply for a Passport?", "answer": "Register on the Passport Seva portal and schedule an appointment at the nearest PSK.", "category": "documents"},
    {"question": "What is DigiLocker?", "answer": "A cloud-based platform for issuance and verification of digital documents.", "category": "documents"},
    {"question": "How to verify a digital certificate?", "answer": "Use the scanner in DigiLocker or the official government QR code verification apps.", "category": "documents"},
    {"question": "What is an E-Shram Card?", "answer": "A unique identification for unorganized workers to get social security benefits.", "category": "documents"},
    {"question": "How to correct birth date in documents?", "answer": "Provide a valid birth certificate or school leaving certificate at the respective issuing authority.", "category": "documents"},
    {"question": "What is a PAN Card?", "answer": "Permanent Account Number issued by the Income Tax Department for financial tracking.", "category": "documents"},
    {"question": "How to track application status?", "answer": "Use the 'Track Status' feature on the respective scheme portal using your application number.", "category": "documents"},
    {"question": "What is a Pensioner ID?", "answer": "A unique ID issued to retired government employees to facilitate pension services.", "category": "documents"},

    # Social Welfare & Social Security (20)
    {"question": "What is the PM Kanya Sumangala Yojana?", "answer": "A cash incentive scheme in UP providing funds for girls from birth to university graduation.", "category": "social"},
    {"question": "What is the National Pension System (NPS)?", "answer": "A voluntary retirement savings scheme providing long-term market-linked returns.", "category": "social"},
    {"question": "What is PM Suraksha Bima Yojana?", "answer": "Accidental insurance of ₹2 lakh for just ₹20 per year for adults.", "category": "social"},
    {"question": "What is PM Jeevan Jyoti Bima Yojana?", "answer": "Life insurance of ₹2 lakh for a premium of ₹436 per year for adults.", "category": "social"},
    {"question": "What is Atal Pension Yojana?", "answer": "A pension scheme for workers in the unorganized sector providing fixed monthly income post-60.", "category": "social"},
    {"question": "What is the benefit of the Senior Citizen Savings Scheme (SCSS)?", "answer": "Provides high-interest quarterly income for individuals over 60.", "category": "social"},
    {"question": "What is the Antyodaya Anna Yojana (AAY)?", "answer": "Provides highly subsidized food grains (35kg/month) to the poorest of the poor households.", "category": "social"},
    {"question": "What is the One Nation One Ration Card (ONORC)?", "answer": "A centralized system allowing beneficiaries to claim food grains anywhere in India using the same card.", "category": "social"},
    {"question": "What is the National Social Assistance Programme (NSAP)?", "answer": "Provides financial assistance to the elderly, widows, and disabled citizens.", "category": "social"},
    {"question": "What is the Widow Pension Scheme?", "answer": "A state-run pension scheme providing monthly financial aid to widowed women from BPL families.", "category": "social"},
    {"question": "What is the Disability Pension Scheme?", "answer": "Monthly financial aid for individuals with more than 80% disability.", "category": "social"},
    {"question": "What is the Indira Gandhi National Old Age Pension Scheme (IGNOAPS)?", "answer": "A central scheme providing monthly pensions to BPL citizens aged 60 and above.", "category": "social"},
    {"question": "How to check PF balance?", "answer": "Use the EPFO UAN portal or send an SMS 'EPFOHO UAN' to 7738299899.", "category": "social"},
    {"question": "What is the Employees Provident Fund (EPF)?", "answer": "A mandatory retirement savings scheme for salaried employees in India.", "category": "social"},
    {"question": "Are there schemes for transgender persons?", "answer": "SMILE (Support for Marginalized Individuals for Livelihood and Enterprise) provides comprehensive support for transgender persons.", "category": "social"},
    {"question": "What is the Garib Kalyan Rojgar Abhiyaan?", "answer": "Provides immediate employment opportunities to migrant workers in rural areas.", "category": "social"},
    {"question": "What is PM-DAKSH?", "answer": "A scheme for upskilling and reskilling marginalized groups for better livelihoods.", "category": "social"},
    {"question": "What is the Rashtriya Vayoshri Yojana?", "answer": "Provides physical aids and assisted-living devices for senior citizens from BPL families.", "category": "social"},
    {"question": "What is the Tribal Development Fund?", "answer": "Provides support for sustainable agriculture and livelihood development in tribal areas.", "category": "social"},
    {"question": "What is the Standup India for SC/ST?", "answer": "Provides loans between ₹10 lakh and ₹1 crore for starting new businesses.", "category": "social"},

    # Education, Students & Youth (30)
    {"question": "What is the PM Research Fellowship (PMRF)?", "answer": "A prestigious fellowship for PhD students in high-tech institutions like IITs and IISc.", "category": "students"},
    {"question": "What is the INSPIRE Scholarship?", "answer": "Supports students pursuing basic and natural science courses for undergraduate and postgraduate studies.", "category": "students"},
    {"question": "What is the KVPY Fellowship?", "answer": "A national fellowship program for students interested in scientific research careers.", "category": "students"},
    {"question": "How to get a free student laptop?", "answer": "Many state governments (like UP, Tamil Nadu) have specific schemes for meritorious students; check your State Education portal.", "category": "students"},
    {"question": "What is the PM-YUVA scheme?", "answer": "Supports young authors and promotes reading, writing, and book culture in India.", "category": "students"},
    {"question": "What is the National Means-cum-Merit Scholarship (NMMS)?", "answer": "Provides ₹12,000 per year to meritorious students of class 9 to 12 from weaker sections.", "category": "students"},
    {"question": "What is the Begum Hazrat Mahal National Scholarship?", "answer": "Supports minority girl students for pursuing higher education.", "category": "students"},
    {"question": "Are there scholarships for PhD students?", "answer": "Yes, schemes like Maulana Azad National Fellowship (MANF) and RGNF provide support for research.", "category": "students"},
    {"question": "What is the AICTE Pragati Scholarship?", "answer": "Provides support to girl students for technical education in AICTE-approved institutions.", "category": "students"},
    {"question": "What is the AICTE Saksham Scholarship?", "answer": "Provides support to specially-abled students for technical education.", "category": "students"},
    {"question": "What is the Ishan Uday Scholarship?", "answer": "A special scholarship scheme for students belonging to the North Eastern Region.", "category": "students"},
    {"question": "What is the Vidyasaarathi portal?", "answer": "A platform for students to apply for various corporate and CSR-funded scholarships.", "category": "students"},
    {"question": "What is the SWAYAM portal?", "answer": "Provides free online courses from Class 9 to Post-Graduation from high-quality faculty.", "category": "students"},
    {"question": "What is NPTEL?", "answer": "Collaborative project of IITs providing online certification in engineering and sciences.", "category": "students"},
    {"question": "How to apply for an education loan interest subsidy?", "answer": "The CSIS (Central Sector Interest Subsidy) scheme provides subsidies on loans taken by EBC students.", "category": "students"},
    {"question": "What is the PM Vidya Lakshmi portal?", "answer": "A single-window for students to apply for education loans and scholarships from multiple banks.", "category": "students"},
    {"question": "What is SHREYAS?", "answer": "A scheme for higher education youth in apprenticeship and skills.", "category": "students"},
    {"question": "What is the National Youth Parliament Festival?", "answer": "A platform for youth to share their voice and views with the government.", "category": "students"},
    {"question": "What is the Nehru Yuva Kendra Sangathan (NYKS)?", "answer": "Promotes youth activities and developmental programs in rural areas.", "category": "students"},
    {"question": "What is the Prime Minister's Special Scholarship Scheme (PMSSS)?", "answer": "Supports students from J&K and Ladakh for pursuing higher education elsewhere.", "category": "students"},
    {"question": "What is the GIAN program?", "answer": "Global Initiative of Academic Networks - brings global experts to teach in Indian institutions.", "category": "students"},
    {"question": "What is the PM Internship Scheme?", "answer": "Provides internship opportunities to youth in top 500 companies with a stipend.", "category": "students"},
    {"question": "What is the Merit-cum-Means Scholarship for Minorities?", "answer": "Supports minority students pursuing professional and technical courses.", "category": "students"},
    {"question": "What is the Post Matric Scholarship for OBCs?", "answer": "Provides financial aid to OBC students for pursuing post-matric courses.", "category": "students"},
    {"question": "How to join the NCC?", "answer": "Apply through your school or college units; NCC provides training and discipline to youth.", "category": "students"},
    {"question": "What is the National Service Scheme (NSS)?", "answer": "Engages youth in community service and social activities.", "category": "students"},
    {"question": "What is the Smart India Hackathon?", "answer": "A national initiative to provide students a platform to solve pressing problems of daily life.", "category": "students"},
    {"question": "What is the MANAK Awards?", "answer": "Aims to foster a culture of innovation among school children.", "category": "students"},
    {"question": "What is the Fit India Movement for youth?", "answer": "Encourages students and youth to adopt a healthy and fit lifestyle.", "category": "students"},
    {"question": "How to get free vocational training?", "answer": "Visit your nearest Jan Shikshan Sansthan (JSS) for localized vocational courses.", "category": "students"},

    # Entrepreneurship & Startup (30)
    {"question": "How to register a startup in India?", "answer": "Register through the Startup India portal with a valid incorporation certificate and a write-up on innovation.", "category": "business"},
    {"question": "What is the Startup India Seed Fund Scheme?", "answer": "Provides financial assistance to startups for proof of concept, prototype development, and market entry.", "category": "business"},
    {"question": "What is the Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)?", "answer": "Provides collateral-free credit to MSMEs.", "category": "business"},
    {"question": "What is the ASPIRE scheme?", "answer": "Promotes innovation, rural industry, and entrepreneurship through technology centers.", "category": "business"},
    {"question": "What is the SFURTI scheme?", "answer": "A scheme of fund for regeneration of traditional industries to make them more competitive.", "category": "business"},
    {"question": "What is the Zero Defect Zero Effect (ZED) scheme?", "answer": "Helps MSMEs improve quality standards and reduce environmental impact.", "category": "business"},
    {"question": "What is the Public Procurement Policy for MSEs?", "answer": "Ensures that 25% of annual procurement by PSUs must be from micro and small enterprises.", "category": "business"},
    {"question": "What is the GeM portal?", "answer": "Government e-Marketplace for public procurement of goods and services online.", "category": "business"},
    {"question": "How to sell on GeM portal?", "answer": "Register as a vendor on the GeM portal with PAN/GST and product details.", "category": "business"},
    {"question": "What is the PM Mudra Yojana for women?", "answer": "Provides priority loans and lower interest rates for women-led micro enterprises.", "category": "business"},
    {"question": "What is the Mahila Coir Yojana?", "answer": "A women-oriented self-employment program in the coir industry.", "category": "business"},
    {"question": "How to get a trade license?", "answer": "Apply at the local municipal corporation office with proof of business premises and ID.", "category": "business"},
    {"question": "What is the Export Promotion Capital Goods (EPCG) scheme?", "answer": "Allows import of capital goods at zero custom duty for export production.", "category": "business"},
    {"question": "What is the PLI scheme?", "answer": "Production Linked Incentive scheme - provides incentives to companies on incremental sales.", "category": "business"},
    {"question": "What is the ATAL Innovation Mission (AIM)?", "answer": "Aims to create and promote an ecosystem of innovation and entrepreneurship across India.", "category": "business"},
    {"question": "What are Atal Tinkering Labs?", "answer": "Innovation workspaces for school students to explore STEM and creative ideas.", "category": "business"},
    {"question": "What is the PM Mega Integrated Textile Region and Apparel (PM MITRA)?", "answer": "Aims to set up world-class industrial infrastructure for the textile sector.", "category": "business"},
    {"question": "What is the Interest Subvention Scheme for MSMEs?", "answer": "Provides interest relief on incremental working capital or new term loans.", "category": "business"},
    {"question": "What is the e-Shram portal for business owners?", "answer": "Business owners can use it to register their unorganized workers for social security.", "category": "business"},
    {"question": "How to get ISO certification subsidy?", "answer": "MSMEs can apply for reimbursement of ISO/other quality certification costs through state/central schemes.", "category": "business"},
    {"question": "What is the Khadi and Village Industries Commission (KVIC)?", "answer": "Promotes and develops rural industries to generate employment.", "category": "business"},
    {"question": "What is the NSIC Single Point Registration?", "answer": "Allows MSEs to participate in government tenders without paying earnest money deposit.", "category": "business"},
    {"question": "What is the Coir Vikas Yojana?", "answer": "Aims to develop the coir industry through skill development and modernization.", "category": "business"},
    {"question": "What is the National Small Industries Corporation (NSIC)?", "answer": "Supports the growth and technology of small-scale industries.", "category": "business"},
    {"question": "How to apply for a small business grant?", "answer": "Check for local 'District Industries Center' (DIC) schemes for sector-specific grants.", "category": "business"},
    {"question": "What is the Skill Loan Scheme?", "answer": "Provides loans between ₹5,000 and ₹1.5 lakh for vocational training.", "category": "business"},
    {"question": "What is the Venture Capital Fund for Scheduled Castes?", "answer": "Supports entrepreneurship among Scheduled Caste entrepreneurs.", "category": "business"},
    {"question": "What is the Self-Employment Lending Scheme?", "answer": "Provides financial aid to unemployed persons from backward classes to start businesses.", "category": "business"},
    {"question": "How to get assistance for international trade fairs?", "answer": "MSME ministry provides subsidies for travel and stall charges for participating in global trade fairs.", "category": "business"},
    {"question": "What is the CLCSS for Technology Upgradation?", "answer": "Provides capital subsidy for induction of well-established and improved technology in MSMEs.", "category": "business"},

    # Specialized (Miscellaneous) (10)
    {"question": "What is the BharatNet project?", "answer": "Aims to provide broadband connectivity to all Gram Panchayats in India.", "category": "misc"},
    {"question": "What is the Digital India Land Records Modernization Programme (DILRMP)?", "answer": "Aims to digitize and modernize all land records across India.", "category": "misc"},
    {"question": "How to report cybercrime?", "answer": "Visit cybercrime.gov.in or dial the national helpline 1930.", "category": "misc"},
    {"question": "What is the PM-WANI scheme?", "answer": "Public Wi-Fi Access Network Interface - aims to increase public Wi-Fi hotspots across India.", "category": "misc"},
    {"question": "What is the Mission Karmayogi?", "answer": "A national program for civil services capacity building.", "category": "misc"},
    {"question": "What is PM Gati Shakti NMP?", "answer": "National Master Plan for multi-modal connectivity to reduce logistics costs.", "category": "misc"},
    {"question": "What is the Agnipath scheme?", "answer": "A scheme for recruitment of youth into the Armed Forces for four years.", "category": "misc"},
    {"question": "What is the PM National Relief Fund?", "answer": "Provides immediate relief for families of those killed in natural calamities and accidents.", "category": "misc"},
    {"question": "How to get info on local state schemes?", "answer": "Visit your state government's 'Integrated State Service Portal' or the SATYA state-filter page.", "category": "misc"},
    {"question": "What is the importance of the SATYA eligibility check?", "answer": "It saves time by identifying schemes only for which you are eligible based on your verified documents.", "category": "misc"}
]

def get_faqs():
    """Return the centralized 100+ FAQ list"""
    return ENGLISH_FAQS
